config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, :controllers => { :registrations => "users/registrations" , 
                                       omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    
    resources :lessons do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    
    resources :enrollments, only: [:new, :create]
  end
  resources :youtube, only: :show
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  
  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @latest_good_reviews = Enrollment.reviewed.latest_good_reviews
    @latest = Course.latest.published.approved
    @top_rated = Course.top_rated.published.approved
    @popular = Course.popular.published.approved
    @purchased_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).order(created_at: :desc).limit(1)
    @popular_tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc).limit(3)
  end
  
  def activity
    if current_user.has_role?(:admin)
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc))
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end
  
  def analytics
    if current_user.has_role?(:admin)
      #@users = User.all
      #@enrollments = Enrollment.all
      #@courses = Course.all
    else
      redirect_to root_path, alert: "You are not authorized to access this page"
    end
  end

end

app/views/home/activity.html.haml
- content_for :title do
  EiuELearning 
  \| 
  Activity
  
%br      

.container  
  
  %h3
    .text-center
      Activity
      .badge.bg-info
        = @activities.count
    %p
    
    %ul.list-group.shadow
      - @activities.each do |activity|
        %li.list-group-item
          /= activity.id
          = activity.created_at.strftime('%d/%m/%Y, %H:%M')
          (#{time_ago_in_words(activity.created_at)})
          = model_label(activity.trackable_type)
          = activity.trackable_type
          /= activity.trackable_id
          - if activity.trackable_type == "Lesson"
            - if Lesson.where(id: activity.trackable_id).any?
              = link_to activity.trackable, course_lesson_path(activity.trackable.course, activity.trackable)
            - else
              that was deleted
          - elsif activity.trackable_type == "Comment"
            - if Comment.where(id: activity.trackable_id).any?
              = link_to activity.trackable.content, course_lesson_path(activity.trackable.lesson.course, activity.trackable.lesson)
            - else
              that was deleted
          - elsif activity.trackable_type == "Course"
            - if Course.where(id: activity.trackable_id).any?
              = link_to activity.trackable, activity.trackable
            - else
              that was deleted
          - else
            = link_to activity.trackable, activity.trackable
          = activity.key
          = crud_label(activity.key.match(/\.(.*)/)[1])
          /= activity.key.match(/\.(.*)/)[1]
          /= activity.owner
          by
          - if activity.owner.present?
            = link_to activity.owner, user_path(activity.owner)
            - if activity.parameters.any?
              = activity.parameters
          - else
            a deleted user
    %p
    != pagy_bootstrap_nav(@pagy)
    %br

app/views/home/analytics.html.haml
- content_for :title do
  EiuELearning 
  \| 
  Analytics

%br      

.container
  %h4.text-center
    New users per day
  .card.shadow
    .card-body
      /= line_chart @users.group_by_day(:created_at).count
      = line_chart charts_users_per_day_path
  %br
  %h4.text-center
    New enrollments per day
  .card.shadow
    .card-body
      /= column_chart @enrollments.group_by_day(:created_at).count
      = column_chart charts_enrollments_per_day_path
  %br
  %h4.text-center
    Most enrolled courses
  
  .card.shadow
    .card-body
      /= pie_chart @courses.group(:enrollments_count).count
      /= pie_chart @enrollments.joins(:course).group(:'courses.title').count
      /= bar_chart @enrollments.joins(:course).group(:'courses.title').count
      = bar_chart charts_course_popularity_path
  %br
  %h4.text-center
    Most paid courses
  .card.shadow
    .card-body
      = bar_chart charts_money_makers_path

app/views/home/index.html.haml
- content_for :title do
  EiuELearning
  \| 
  Online Courses - Learn Anything, On Your Schedule
  
.container  
  .jumbotron
    .display-4
      %br
  %section.vh-70.bg-image{style: "background-image: url('https://eiu.edu.vn/wp-content/uploads/2021/09/apply-2.jpg');"}
    .py-5
      .container.px-lg-5
        .p-4.p-lg-5.bg-light.rounded-3.text-center
          .m-4.m-lg-5
            %h1.display-5.fw-bold Learn without limits
            %p.fs-4
            | Start, switch, or advance your career with more than 5,400 courses, Professional Certificates, and degrees from world-class universities and companies.
            %br 
            -if current_user
              
            - else    
              .nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_registration_path)}", style: "margin-right: 10px"}
                = link_to 'Join for free', new_user_registration_path, class: 'btn btn-lg btn-info'
    .p-4
  // basic info
  %br
  .card-group
    .card.card-body
      %h1
        .fa.fa-graduation-cap
      = pluralize(Course.approved.published.count, 'online courses')  
      /= Course.count
      /online courses
      .row
      Explore a variety of fresh topics
    .card.card-body
      %h1
        .fa.fa-chalkboard-teacher
        /.fa.fa-brain
      = Course.distinct.count(:user_id)
      expert instructors
      .row
      Find the right instructor for you
    .card.card-body
      %h1
        .fa.fa-user-graduate
      = User.count
      active learners
      .row
      Join the knowledge sharing community
    .card.card-body
      %h1
        .fa.fa-infinity
      Lifetime access
      .row
      Learn on your schedule
  
  %p

  //keeo studying 
  - if current_user
    .row
      .col-md-8.col-md-8
        .card.bg-light.text-dark{:style => "text-align:center;margin-top:20px;"}
          %img.card-img{alt: "Stony Beach", src: "https://thumbs.dreamstime.com/b/welcome-letters-banner-overlapping-colorful-squares-background-121137709.jpg"}/
      .col-md-4.col-md-4
        .card
          %img.img-fluid{src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJS1z2sOXYMEg_OdDCQIJGNMAYejO1p_RkrQ&usqp=CAU"}/
          %a{href: "#!"}
            .mask{style: "background-color: rgba(251, 251, 251, 0.15);"}
          .card-body
            %ul.navbar-nav.mr-auto{style: "text-align: center"}
              %h5.card-title Continue Learning
              %h7.card-text
                %a.nav-link{href: "/courses/purchased "} ALL MY PURCHASED COURSES
              %h7.card-text 
                %a.nav-link{href: "/courses/pending_review"} ALL MY PENDING REVIEWS

    
    %hr
  
  //new about school
  %h1
    .text-center
      EIU News
  %p
  .row.row-cols-1.row-cols-md-3.g-4
    .col
      .card.h-100
        %img.card-img-top{alt: "...", src: "https://eiu.edu.vn/wp-content/uploads/2021/06/A4A9933-2048x1366.jpg"}/
        .card-body
          %h5.card-title 
            %a.nav-link{href: "https://eiu.edu.vn/tuyen-sinh/tuyen-sinh-2023/hoc-phi-hoc-bong/"} Scholarships And Tuition Fees
          %p.card-text This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.
  
    .col
      .card.h-100
        %img.card-img-top{alt: "...", src: "https://eiu.edu.vn/wp-content/uploads/2020/08/LIB-Journals.jpg"}/
        .card-body
          %h5.card-title
            %a.nav-link{href: "https://eiu.edu.vn/kham-pha/doi-ngu-eiu/"} EIU Team
          %p.card-text This card has supporting text below as a natural lead-in to additional content.
  
    .col
      .card.h-100
        %img.card-img-top{alt: "...", src: "https://eiu.edu.vn/wp-content/uploads/2021/06/TUA3067-2048x1366.jpg"}/
        .card-body
          %h5.card-title
            %a.nav-link{href: "https://eiu.edu.vn/tuyen-sinh/tai-sao-lua-chon-eiu/"} Education Programs
          %p.card-text This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.
  
  %br
  
  %hr
  
  // video intro
  %h1
    .text-center EIU Environment
  %p
  .card{style: "max-width: 2000px"}
    .row.g-0
      .col-md-5{style: "position: center; left: 0; right: 0; margin: 0 auto;"} 
        %h5.card-title EIU Studying Environment
        %video.img-fluid{autoplay: "", loop: "", muted: ""}
          %source{src: "https://mdbcdn.b-cdn.net/img/video/forest.mp4", type: "video/mp4"}
          
      .col-md-3{style: "padding-top: 0px"}
        .card{style: "position: center; left: 0; right: 0; margin: 0 auto; max-width: 360px;"}
          %a{href: "https://eiu.edu.vn/kham-pha/tin-tuc-su-kien/tin-tuc/"}
            %img.card-img-top{alt: "...", src: "https://eiu.edu.vn/wp-content/uploads/2022/03/website-thumbnail-VI-02-265x355.png"}/
  
      .col-md-3{style: "padding-top: 0px"}
        .card{style: "position: center; left: 0; right: 0; margin: 0 auto; max-width: 360px;"}
          %a{href: "http://becamex.com.vn/"}
            %img.card-img-top{alt: "...", src: "https://eiu.edu.vn/wp-content/uploads/2022/03/website-thumbnail-VI-01-265x355.png"}/
  // student comments
  
  %p
  %h1
    .text-center
      What our students say...
  %p
  
  #carouselExampleControls.carousel.slide{"data-bs-ride" => "carousel"}
    .carousel-inner
      .carousel-item.active
        %img.d-block.w-100{alt: "...", src: "https://5starcourses.co.uk/wp-content/uploads/2020/02/3-2.png"}/
      .carousel-item
        %img.d-block.w-100{alt: "...", src: "https://5starcourses.co.uk/wp-content/uploads/2020/02/2-2.png"}/
      .carousel-item
        %img.d-block.w-100{alt: "...", src: "https://5starcourses.co.uk/wp-content/uploads/2020/02/1-1.png"}/
    %a.carousel-control-prev.bg-transparent.w-aut{"data-bs-slide" => "prev", "data-bs-target" => "#carouselExampleControls", type: "button"}
      %span.carousel-control-prev-icon{"aria-hidden" => "true"}
    %a.carousel-control-next.bg-transparent.w-aut{"data-bs-slide" => "next", "data-bs-target" => "#carouselExampleControls", type: "button"}
      %span.carousel-control-next-icon{"aria-hidden" => "true"}