config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, :controllers => { :registrations => "users/registrations" , 
                                       omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    
    resources :lessons do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    
    resources :enrollments, only: [:new, :create]
  end
  resources :youtube, only: :show
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  
  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  belongs_to :user, counter_cache: true
  
  validates :user, :course, presence: true
  
  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :course_id  #user cant be subscribed to the same course twice
  validates_uniqueness_of :course_id, scope: :user_id  #user cant be subscribed to the same course twice

  validate :cant_subscribe_to_own_course  #user can't create a subscription if course.user == current_user.id
  
  scope :pending_review, -> { where(rating: [0, nil, ""], review: [0, nil, ""]) }
  scope :reviewed, -> { where.not(review: [0, nil, ""]) }
  scope :latest_good_reviews, -> { order(rating: :desc, created_at: :desc).limit(3) }
  
  extend FriendlyId
  friendly_id :to_s, use: :slugged
  
  def self.ransackable_attributes(auth_object = nil)
    ["approved", "average_rating", "created_at", "description", "enrollments_count", "id", "language", "lessons_count", "level", "price", "published", "short_description", "slug", "title", "updated_at", "user_id"]
  end
  
  def self.ransackable_associations(auth_object = nil)
    ["course", "user"]
  end
  
  def to_s
    user.to_s + " " + course.to_s
  end

  after_save do
    unless rating.nil? || rating.zero?
      course.update_rating
    end
  end

  after_destroy do
    course.update_rating
  end

  protected
  def cant_subscribe_to_own_course
    if self.new_record?
      if self.user_id.present?
        if self.user_id == course.user_id
          errors.add(:base, "You can not subscribe to your own course")
        end
      end
    end
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:certificate]
  before_action :set_enrollment, only: [:show, :edit, :update, :destroy, :certificate]
  before_action :set_coruse, only: [:new, :create]

  # GET /enrollments or /enrollments.json
  def index
    #@enrollments = Enrollment.all
    #@pagy, @enrollments = pagy(Enrollment.all)
    @ransack_path = enrollments_path
    
    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    
    authorize @enrollments
  end
  
  def my_students
    @ransack_path = my_students_enrollments_path
    @q = Enrollment.joins(:course).where(courses: {user: current_user}).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render 'index'
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
    authorize @enrollment
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = current_user.buy_course(@course)
    EnrollmentMailer.student_enrollment(@enrollment).deliver_later
    EnrollmentMailer.teacher_enrollment(@enrollment).deliver_later
    redirect_to course_path(@course), notice: "You are enrolled!"
    #if @course.price > 0
      #flash[:alert] = "You can not access paid courses yet."
      #redirect_to new_course_enrollment_path(@course)
    #else
      #@enrollment = current_user.buy_course(@course)
      #redirect_to course_path(@course), notice: "You are enrolled!"
    #end  
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def certificate
    authorize @enrollment, :certificate?
    respond_to do |format|
      format.pdf do
        render pdf: "#{@enrollment.course.title}, #{@enrollment.user.email}",
               page_size: 'A4',
               template: 'enrollments/certificate.pdf.haml'
      end
    end
  end
  
  def self.ransackable_attributes
    ["comments_count", "confirmation_sent_at", "confirmation_token", "confirmed_at", "courses_count", "created_at", "current_sign_in_at", "current_sign_in_ip", "efresh_token", "email", "encrypted_password", "enrollments_count", "expires", "expires_at", "id", "image", "invitation_accepted_at", "invitation_created_at", "invitation_limit", "invitation_sent_at", "invitation_token", "invitations_count", "invited_by_id", "invited_by_type", "last_sign_in_at", "last_sign_in_ip", "name", "provider", "remember_created_at", "reset_password_sent_at", "reset_password_token", "sign_in_count", "slug", "token", "uid", "unconfirmed_email", "updated_at", "user_lessons_count"]
  end

  private
    def set_coruse
      #binding.pry
      @course = Course.friendly.find(params[:course_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      #params.require(:enrollment).permit(:course_id, :user_id, :rating, :review)
      params.require(:enrollment).permit(:rating, :review)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.haml
.card
  .card-header
    .fa.fa-user
    = link_to enrollment.user.username, user_path(enrollment.user)
    .fa.fa-clock
    = time_ago_in_words(enrollment.updated_at)
    .fa.fa-graduation-cap
    = link_to enrollment.course, course_path(enrollment.course)
  .card-body
    .text-warning.fa.fa-star
    %b= enrollment.rating
    .fa.fa-comment
    %small= enrollment.review
  - if current_user
    .card-footer
      - if policy(enrollment).edit?
        = link_to 'Edit Review', edit_enrollment_path(enrollment)

app/views/enrollments/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@enrollment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    /= f.input :rating, collection: 1..5, as: :radio_buttons
    = f.radio_button :rating, 1, as: :radio_buttons 
    1
    %br
    = f.radio_button :rating, 2, as: :radio_buttons 
    2
    %br
    = f.radio_button :rating, 3, as: :radio_buttons 
    3
    %br
    = f.radio_button :rating, 4, as: :radio_buttons 
    4
    %br
    = f.radio_button :rating, 5, as: :radio_buttons 
    5
    = f.input :review

  %br  
  .form-actions
    = f.button :submit

app/views/enrollments/certificate.pdf.haml
%center
  %div{:style => "width:1200px; height:800px; padding:20px; text-align:center; border: 10px solid #563d7c"}
    %div{:style => "width:1150px; height:750px; padding:20px; text-align:center; border: 5px solid #563d7c"}
      %br
      %br
      %br
      %br
      %span{:style => "font-size:50px; font-weight:bold"} Certificate of Completion

      /%center
      /  %h1 
      /    Certificate of Completion
      %br
      %br
      %br
      %br
      %p
      %h3
        This is to certify that the owner of the email address
      %h2
        %u
          = @enrollment.user.email
      %h3
        has successfully completed the course
      %h2
        %u
          = @enrollment.course.title
      %h3
        on the EIU-E-Learning.com platform

      %p

      %br
      %br
      %br
      %br
      %b Certificate id: 
      #{@enrollment.slug}

      %p

      %b Certificate url: 
      #{request.base_url}#{request.original_fullpath}

      %p
      %b Registration date: 
      #{@enrollment.created_at.strftime('%d-%b-%Y')}

      %br
      %br
      %br
      %center
        %h3
          = image_tag wicked_pdf_asset_base64('eiulogo.png'), height: "30", width: "auto"
          %p
          www.EIU-E-Learning.com

app/views/enrollments/edit.html.haml
- content_for :title do
  EiuELearning
  \| 
  Editing
  = @enrollment.to_s
%br      

.container
  .card
    .card-header
      %h3
        .text-warning.fa.fa-star
        Add a Review
    .card-body
      = render 'form'
    .card-footer
      = link_to 'Show Review', @enrollment
      \|
      = link_to 'Back to course', course_path(@enrollment.course)

app/views/enrollments/index.html.haml
- content_for :title do
  EiuELearning 
  \| 
  = action_name.humanize
  enrollments

%br
.container

  %h3
    .text-center
      .fa.fa-lock-open
      = action_name.humanize
      enrollments
      .badge.bg-info
        = @enrollments.count
  %p
  
  = search_form_for @q, url: @ransack_path do |f|
    = f.search_field :user_email_cont, placeholder: 'user email'
    = f.search_field :course_title_cont, placeholder: 'course title'
    = f.search_field :course_user_email_cont, placeholder: 'teacher'
    = f.search_field :price_eq, placeholder: 'price'
    /= f.search_field :rating_eq, placeholder: 'rating'
    = f.submit
  = link_to 'refresh', @ransack_path
  
  .table-responsive
    %table.table.table-bordered.table-striped.table-sm
      %thead
        %tr
          /%th ID
          %th
            = sort_link(@q, :user_email, "User")
            /.fa.fa-user
            /User
          %th
            = sort_link(@q, :created_at)
            /.fa.fa-clock
            /.fa.fa-lock-open
            /bought
          %th
            = sort_link(@q, :course_title, "Course")
            /.fa.fa-graduation-cap
            /Course
          %th Teacher  
          %th 
            = sort_link(@q, :price)
            /.fa.fa-dollar-sign
            /Price
          %th 
            = sort_link(@q, :updated_at)
            /.row
            .text-warning.fa.fa-clock
            /Reviewed on
          %th 
            = sort_link(@q, :rating)
            /.text-warning.fa.fa-star
            /Rating
          %th 
            Review
            /.text-warning.fa.fa-comment
          %th Progress  
          %th Certificate
          %th
          %th
  
  
      %tbody
        - @enrollments.each do |enrollment|
          %tr
            /%td= enrollment.id
            %td= link_to enrollment.user.email, user_path(enrollment.user)
            %td= enrollment.created_at.strftime("%d/%b/%Y, %H:%M")
            %td= link_to enrollment.course, course_path(enrollment.course)
            %td= link_to enrollment.course.user, user_path(enrollment.course.user)
            %td= number_to_currency(enrollment.price)
            %td
              - if enrollment.rating.present?
                = enrollment.updated_at.strftime("%d/%b/%Y, %H:%M")
            %td= enrollment.rating
            %td= enrollment.review
            %td= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0)
            %td= link_to 'Certificate', certificate_enrollment_path(enrollment, format: :pdf)
            %td= link_to 'See Review', enrollment
            %td
              - if policy(enrollment).edit?
                = link_to 'Add Review', edit_enrollment_path(enrollment)
            %td
              - if policy(enrollment).destroy?
                = link_to 'Delete Enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' }
  != pagy_bootstrap_nav(@pagy)
  %br
  
  /= link_to 'New Enrollment', new_enrollment_path

app/views/enrollments/new.html.haml
- content_for :title do
  EiuELearning 
  \| 
  New enrollment
%br
.container
  .card
    .card-header
      %h3
        .fa.fa-graduation-cap
        = link_to @course.title, course_path(@course)
        %hr
        .fa.fa-lock-open
        Enroll the course for free
    .card-body
      = form_tag course_enrollments_path(@course) do
        = submit_tag "Confirm", class: 'btn btn-lg btn-success'
    .card-footer
      = link_to 'Back', course_path(@course)

app/views/enrollments/show.html.haml
%br      

.container
  = render 'enrollments/enrollment', enrollment: @enrollment