config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, :controllers => { :registrations => "users/registrations" , 
                                       omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    
    resources :lessons do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    
    resources :enrollments, only: [:new, :create]
  end
  resources :youtube, only: :show
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  
  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/course.rb
class Course < ApplicationRecord
  after_initialize :set_defaults, unless: :persisted?
  
  
  validates :title,  presence: true
  validates :description, length: { minimum: 5 }
  validates :short_description, length: { maximum: 300 }
  belongs_to :user, counter_cache: true
  has_many :lessons, dependent: :destroy
  has_many :enrollments
  has_many :enrollments, dependent: :restrict_with_error
  has_many :user_lessons, through: :lessons
  has_many :course_tags, inverse_of: :course, dependent: :destroy
  has_many :tags, through: :course_tags
  
  validates :title, uniqueness: true, length: { maximum: 70 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  
  scope :latest, -> { limit(3).order(created_at: :desc) }
  scope :top_rated, -> { limit(3).order(average_rating: :desc, created_at: :desc) }
  scope :popular, -> { limit(3).order(enrollments_count: :desc, created_at: :desc) }
  scope :published, -> { where(published: true) }
  scope :unpublished, -> { where(published: false) }
  scope :approved, -> { where(approved: true) }
  scope :unapproved, -> { where(approved: false) }
  
  has_one_attached :avatar
  validates :avatar, presence: true,
    content_type: ['image/png', 'image/jpg', 'image/jpeg'], 
    size: { less_than: 500.kilobytes , message: 'size should be under 500 kilobytes' }
  
  def to_s
    title
  end
  has_rich_text :description
  extend FriendlyId
  friendly_id :title, use: :slugged

  LANGUAGES = [:"English", :"Vietnamese"]
  def self.languages
    LANGUAGES.map { |language| [language, language] }
  end

  LEVELS = [:"All levels", :"Beginner", :"Intermediate", :"Advanced"]
  def self.levels
    LEVELS.map { |level| [level, level] }
  end
  #
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user }
  
  def bought(user)
    self.enrollments.where(user_id: [user.id], course_id: [self.id]).empty?
  end
  
  def progress(user)
    unless self.lessons_count == 0
      user_lessons.where(user: user).count/self.lessons_count.to_f*100
    end
  end
  
  def update_rating
    if enrollments.any? && enrollments.where.not(rating: nil).any?
      update_column :average_rating, (enrollments.average(:rating).round(2).to_f)
    else
      update_column :average_rating, (0)
    end
  end
  
  def self.ransackable_attributes(auth_object = nil)
    ["approved", "average_rating", "created_at", "description", "enrollments_count", "id", "language", "lessons_count", "level", "price", "published", "short_description", "slug", "title", "updated_at", "user_id"]
  end
 
  def self.ransackable_associations(auth_object = nil)
    ["activities", "avatar_attachment", "avatar_blob", "course_tags", "enrollments", "lessons", "rich_text_description", "tags", "user", "user_lessons"]
  end
  
  
  def set_defaults
    self.approved = false
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show index]
  before_action :set_course, only: [:show, :edit, :update, :destroy, :approve, :unapprove, :analytics]
  before_action :set_tags, only: %i[index purchased pending_review created unapproved]


  # GET /courses or /courses.json
  def index
    @ransack_path = courses_path
    @ransack_courses = Course.published.approved.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, course_tags: :tag))
  end
  
  def purchased
    
    @ransack_path = purchased_courses_path
    @ransack_courses = Course.joins(:enrollments).where(enrollments: {user: current_user}).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end

  def pending_review
    @ransack_path = pending_review_courses_path
    @ransack_courses = Course.joins(:enrollments).merge(Enrollment.pending_review.where(user: current_user)).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, course_tags: :tag))
    render 'index'
  end

  def created
    
    @ransack_path = created_courses_path
    @ransack_courses = Course.where(user: current_user).ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :course_tags => :tag))
    @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    render 'index'
  end
  
  def unapproved
    @ransack_path = unapproved_courses_path
    @ransack_courses = Course.unapproved.published.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, course_tags: :tag))
    render 'index'
  end

  def approve
    authorize @course, :approve? # admin
    if @course.approved?
      @course.update(approved: false)
    else
      @course.update(approved: true)
    end
    redirect_to @course, notice: "Course approval: #{@course.approved}"
  end

  def unapprove
    
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to @course, notice: "Course upapproved and hidden!"
  end
  
  def analytics
    authorize @course, :owner?
  end

  # GET /courses/1 or /courses/1.json
  def show
    authorize @course
    @lessons = @course.lessons.rank(:row_order)
    @enrollments_with_review = @course.enrollments.reviewed
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course
    @tags = Tag.all
  end

  # GET /courses/1/edit
  def edit
    authorize @course
    @tags = Tag.all
  end

  # POST /courses or /courses.json
  def create
    #binding.pry
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        @tags = Tag.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        @tags = Tag.all
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to @course, alert: 'Course has enrollments. Can not be destroyed.'
    end
  end

  private
  
    def set_tags
      @tags = Tag.all.where.not(course_tags_count: 0).order(course_tags_count: :desc)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :price,
        :published, :language, :level, :avatar, tag_ids: [])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enrollment_button(course)
    if current_user
      if course.user == current_user
        link_to course_path(course) do
          "You created this course " +
          number_to_currency(course.price)
        end
      elsif course.enrollments.where(user: current_user).any?
        link_to course_path(course) do
          #"You bought this course. Keep learning" +
          "<i class='fa fa-spinner'></i>".html_safe + " " +
          number_to_percentage(course.progress(current_user), precision: 0)
        end
      elsif course.price > 0
        link_to number_to_currency(course.price), new_course_enrollment_path(course), class: 'btn btn-success'
      else
        link_to "Free", new_course_enrollment_path(course), class: 'btn btn-success'
      end
      #logic to buy
    else
      link_to "Check price", new_course_enrollment_path(course), class: "btn btn-md btn-success"
    end
  end
  
  def review_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if user_course.pending_review.any?
          link_to edit_enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='text-dark fa fa-question'></i>".html_safe + " " +
            'Add a review'
          end
        else
          link_to enrollment_path(user_course.first) do
            "<i class='text-warning fa fa-star'></i>".html_safe + " " +
            "<i class='fa fa-check'></i>".html_safe + " " +
            "<i class='text-success fa fa-check'></i>".html_safe + " " +
            'Thanks for reviewing!'
          end
        end
      end
    end
  end
  
  def certificate_button(course)
    user_course = course.enrollments.where(user: current_user)
    if current_user
      if user_course.any?
        if course.progress(current_user) == 100
          link_to certificate_enrollment_path(user_course.first, format: :pdf) do
            "<i class='text-danger fa fa-file-pdf'></i>".html_safe + " " +
            "Certificate of Completion"
          end
        else
          "Certificate available after completion"
        end
      end
    end
  end
  
end

app/views/courses/_course.html.haml
   
        
.col-xs-12.col-sm-6.col-md-12
  / Card
  .card
    / Card image
    .card-header
      .fa.fa-graduation-cap
      = link_to course.title, course_path(course)
    .view.overlay
      %img.card-img-top{alt: "Card image cap", src: "https://qph.cf2.quoracdn.net/main-qimg-e7be1823b5ba0df187741d7f9eae9c67-lq"}/
      %a{href: "#!"}
        .mask.rgba-white-slight
    / Card content
    .card-body
      / Title
      .card-content
        %h4.card-title Course Intro
        / Text
        %p.card-text= course.short_description
        / Provides extra visual weight and identifies the primary action in a set of buttons
      .card-read-more
      %br
        .text-center
          = enrollment_button(course)
          .row
          = review_button(course)
          .row
          = certificate_button(course)
    .card-footer
      .row
        .col-md-6
          .text-warning.fa.fa-star
          %b= course.average_rating
          /Enrollments count:
          /= course.enrollments.count
          /Counter cache enrollments count:
          (
          .fa.fa-user-graduate
          = course.enrollments_count
          )
          .fa.fa-tasks
          = course.lessons_count
        .col-md-6
          .text-right
            .fa.fa-chalkboard-teacher
            = link_to course.user.username, user_path(course.user)
    - if current_user  
      - if policy(course).owner?
        .card-footer
          = link_to 'Add lesson', new_course_lesson_path(course, @lesson), class: 'btn btn-outline-success btn-sm'
          = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-outline-warning'
          - if policy(course).destroy?
            = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'
          = link_to analytics_course_path(course), class: 'btn btn-sm btn-outline-info' do
            .fa.fa-chart-bar
            Analytics  
      - if policy(course).admin_or_owner?
        .card-footer
          - if course.published?
            .badge.bg-info published
          - else
            .badge.bg-infounpublished
          - if course.approved?
            .badge.bg-info approved
          - else
            .badge.bg-info unapproved
          - if policy(course).approve?
            - if course.approved?
              = link_to 'unapprove', unapprove_course_path(course), method: :patch, class: 'btn btn-sm btn-outline-danger'
            - else
              = link_to 'approve', approve_course_path(course), method: :patch, class: 'btn btn-sm btn-outline-success' 
    - if course.tags.any?
      .card-footer
        - course.tags.each do |tag|
          .badge.bg-info
            = tag.name           
  %br

app/views/courses/_course_landscape.html.haml
%br
.container.py-1.my-1
  .card.shadow
    .card-body
      .row
        .col-md-5
          - if course.avatar.attached?
            = link_to course_path(course) do
              = image_tag course.avatar, loading: "lazy", height: "170px", width: "100%"
        .col-md-4
          %b= link_to course.title, course_path(course)
          .text-warning.fa.fa-star
          %b= course.average_rating
          (
          .fa.fa-user-graduate
          = course.enrollments_count
          )
          .fa.fa-tasks
          = course.lessons_count
          %br
          - if course.tags.any?
            - course.tags.each do |tag|
              .badge.badge-info
                = tag.name
          %br
          - if course.user 
            - if course.user.image?
              = image_tag course.user.image, size: '20x20', alt: "#{course.user.email}", class: 'rounded-circle'
            = link_to course.user.username, user_path(course.user)
        .col-md-3
          .text-center
            = enrollment_button(course)
            .row
            = review_button(course)
            .row
            %small= certificate_button(course)
        %br

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
  
  .form-inputs
    = f.input :title
    
    /= f.label :avatar
    .row
    - if @course.avatar.attached?
      = image_tag @course.avatar, width: "200px"
      /= @course.avatar.content_type
      /= @course.avatar.key
      .row
      = @course.avatar.filename
      /= @course.avatar.metadata
      /= @course.avatar.byte_size
      /= @course.avatar.checksum
    .row
    /= f.file_field :avatar 
    /%small= f.error :avatar, class: 'text-danger'
    %br
    = f.input :avatar
    %br
    .row
    /= f.label :description
    /= f.rich_text_area :description
    /%small= f.error :description, class: 'text-danger'
    = f.input :description, as: :rich_text_area
    = f.input :short_description
    /= f.input :language, collection: [ "English", "Polish", "Russian"]
    = f.input :language, collection: Course.languages, include_blank: true
    /= f.input :level, collection: [ "Beginner", "Intermediate", "Advanced"]
    = f.input :level, collection: Course.levels, include_blank: true
    = f.input :price
    = f.input :published
    = f.label :tags
    = f.select :tag_ids, @tags.all.pluck(:name, :id), {}, { multiple: true, class: "selectize-tags" }


  .form-actions
    = f.button :submit      

app/views/courses/analytics.html.haml
- content_for :title do
  EiuELearning 
  |
  = @course.title
  Analytics
%br      

.container
  = link_to 'Courses', courses_path
  |
  = link_to course_path(@course) do
    .fa.fa-graduation-cap
    = @course.title
  |
  = link_to analytics_course_path(@course) do
    .fa.fa-chart-bar
    Analytics
  
  /%h4.text-center 
  /  Analtycs for #{@course.title}
  %h4.text-center
    Enrollments per day, quantity
  = line_chart @course.enrollments.group_by_day(:created_at).count
  %br
  %h4.text-center
    Enrollments per day, revenue
  = line_chart @course.enrollments.group_by_day(:created_at).sum(:price)
  %br
  %h4.text-center
    Unique user views (how many unique users viewed the lesson)
  = bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count
  %br
  %h4.text-center
    Impressions per lesson (how many times the lesson was opened)
  = bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impressions)

app/views/courses/edit.html.haml
- content_for :title do
  EiuELearning
  \| 
  Editing
  = @course.title
  
%br  
.container    
  .card
    .card-header
      %h3
        .fa.fa-graduation-cap
        Editing course
    .card-body
      = render 'form'
  
    .card-footer
      = link_to 'Show', @course
      \|
      = link_to 'Back', courses_path

app/views/courses/index.html.haml
- content_for :title do
  EiuELearning
  \| 
  = action_name.humanize
  courses

%br      

.container
  .row
    .col-md-3
      %h3
      .text-center
        .fa.fa-graduation-cap
        = action_name.humanize
        courses
        .badge.bg-info
          = @courses.count
        
      /= search_form_for @q do |f|
      = search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f|
        = f.label :title
        = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'
        .row
        %br
        = f.label :tag
        = f.search_field :course_tags_tag_name_cont, placeholder: 'Tag name', class: 'form-control form-control-sm'
        /= f.select :course_tags_tag_name_cont, @tags, {include_blank: true}, class: "form-control  form-control-sm"
        .row
        %br
        = f.label :language
        .row
        = f.select :language_cont, Course.languages, {include_blank: true}, class: "form-control  form-control-sm"
        .row
        %br
        = f.label :level
        .row
        = f.select :level_cont, Course.levels, {include_blank: true}, class: "form-control  form-control-sm"
        .row
        %br
        = f.label :price
        = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
        %br
        = f.label :teacher
        = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
        .row
        %br
        = sort_link(@ransack_courses, :price, class: "btn btn-outline-info py-1")
        .row
        = sort_link(@ransack_courses, :average_rating, "Top Rated", class: "btn btn-outline-info my-1")
        .row
        = sort_link(@ransack_courses, :enrollments_count, "Most Popular", class: "btn btn-outline-info py-1")
        .row
        = sort_link(@ransack_courses, :created_at, "Newest", class: "btn btn-outline-info py-1 my-1")
        .row
        = f.submit
      = link_to 'refresh', @ransack_path, class: "btn btn-outline-success py-1 my-1"
      %hr
      .row
      - @tags.each do |tag|
        = link_to controller: controller_name, action: action_name, courses_search: {course_tags_tag_id_eq: tag.id} do
          .badge.bg-info
            = tag.name

      %p
      %br
      
      
    .col-md-9   
      %section.wrapper
        .container-fostrap
          .content
            .row
              - @courses.each do |course|
                = render 'courses/course_landscape', course: course
                %br
      %br          
      != pagy_bootstrap_nav(@pagy)  
    %br    
  %br      
%br



      
      
      

app/views/courses/new.html.haml
- content_for :title do
  EiuELearning
  \| 
  New course
  
%br  
.container  
  .card
    .card-header
      %h3
        .fa.fa-graduation-cap
        New course
    .card-body
      = render 'form'
  
    .card-footer
      = link_to 'Back', courses_path

app/views/courses/show.html.haml
- content_for :title do
  EiuELearning
  | 
  = @course.title

%br  
.container  
  = link_to 'Courses', courses_path
  |
  = link_to @course.title, course_path(@course)
  %p
  
  .row
    .col-lg-8.order-1.order-lg-1
      .jumbotron.bg-light.text-dark.rounded
        .container
          %h3
            .fa.fa-graduation-cap
            = @course.title
            /.row
            /HAS AVATAR?
            /= @course.avatar.attached?
            /- if @course.avatar.attached?
            /  = image_tag @course.avatar, width: "200px"
          /.p-3
          %hr
          .fa.fa-clock
          Created
          = @course.created_at.strftime("%m/%Y")
          .fa.fa-clock
          Last updated
          = @course.updated_at.strftime("%m/%Y")
          .row
          .fa.fa-globe-africa
          = @course.language
          .row
          .fa.fa-signal
          = @course.level
          .row
          .fa.fa-file-pdf
          Certificate of Completion
          %hr
          = @course.description
  
      %h4
        .fa.fa-tasks
        = pluralize(@course.lessons_count, 'lesson')
        .float-end
          .fa.fa-spinner
          = number_to_percentage(@course.progress(current_user), precision: 0)
      .list-group.lesson-sortable
        - @lessons.each do |lesson|
          = content_tag "div", id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: course_lesson_sort_path(@course, lesson)} do
            .list-group-item
              .fa.fa-sort.all-scroll{:style => "cursor: grab;"}
              = render 'lessons/lesson_preview', lesson: lesson
      %p
  
      %h4
        .fa.fa-comment
        = pluralize(@enrollments_with_review.count, 'review')
  
      - @enrollments_with_review.each do |enrollment|
        = render 'enrollments/enrollment', enrollment: enrollment
      %p  
      
    .col-lg-4.order-0.order-lg-1
      .sticky-top
        = render 'courses/course', course: @course
      %p
  %h4 
    .fa.fa-graduation-cap
    Similar Courses
  
  /Current course tags
  /= @course.tags.pluck(:id)
  /.row
  /All course tags
  - Course.all.where.not(id: @course.id).each do |course|
    .row
    /= course.tags.pluck(:id)
    - unless @course.tags.pluck(:id).intersection(course.tags.pluck(:id)).count.zero?
      .card-columns
        = render 'courses/course', course: course
  