config/routes.rb
Rails.application.routes.draw do
  
  #devise_for :users
  devise_for :users, :controllers => { :registrations => "users/registrations" , 
                                       omniauth_callbacks: 'users/omniauth_callbacks'}
  
  resources :enrollments do
    get :my_students, on: :collection
    member do
      get :certificate
    end
  end
  
  resources :tags, only: [:create, :index, :destroy]
  resources :courses do
    get :purchased, :pending_review, :created, :unapproved, on: :collection
    member do
      get :analytics
      patch :approve
      patch :unapprove
    end
    
    resources :lessons do
      resources :comments, except: [:index]
      put :sort
      member do
        delete :delete_video
      end
    end
    
    resources :enrollments, only: [:new, :create]
  end
  resources :youtube, only: :show
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'activity', to: 'home#activity'
  get 'analytics', to: 'home#analytics'
  
  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'course_popularity'
    get 'money_makers'
  end
  
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.haml
%hr
%footer.footer
  .container
    .row
      .col-md-4
        Copyright
        © 
        = Time.now.year
        CoursePlatform Sp. z o.o.
        .row
        .fa.fa-envelope
        = mail_to 'phu.vo.set17@eiu.edu.vn'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms and conditions
      .col-md-4
        About us
        .row
        = link_to 'Create Your Class', new_course_path
%br

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light{:style => "background-color: #e3f2fd;"}
  .container-fluid
    %a.navbar-brand{:href => "/"}
      %img{alt: "EIU logo", height: "30", src: "https://cdn.haitrieu.com/wp-content/uploads/2021/12/Logo-DH-Quoc-Te-Mien-Dong-EIU.png", width: "100"}
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto
        - if current_user
          %ul.navbar-nav.me-auto
            = link_to courses_path, class: "nav-link #{'active fw-bold' if current_page?(root_path)}" do
              .fa.fa-graduation-cap
              Courses
        - if current_user 
          - if current_user.has_role?(:admin) 
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                .fa.fa-user
                %b Admin
              %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                = link_to unapproved_courses_path, class: "dropdown-item" do
                  .fa.fa-graduation-cap
                  %b Unapproved courses
                  .badge.bg-info
                    = Course.unapproved.count
                = link_to users_path,  class: "dropdown-item" do
                  .fa.fa-users
                  %b Users 
                  .badge.bg-info
                    = User.count
                = link_to enrollments_path, class: "dropdown-item" do
                  .fa.fa-lock-open
                  %b Enrollments
                  .badge.bg-info
                    = Enrollment.count
                = link_to activity_path, class: "dropdown-item" do
                  .fa.fa-bell
                  %b Activity 
                = link_to analytics_path, class: "dropdown-item" do
                  .fa.fa-chart-line
                  %b Analytics  
                = link_to tags_path, class: "dropdown-item" do
                  .fa.fa-tags
                  %b Tags  
        - if current_user 
          - if current_user.has_role?(:student) 
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                .fa.fa-graduation-cap
                %b Learning
              %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                = link_to purchased_courses_path,  class: "dropdown-item" do
                  .fa.fa-graduation-cap
                  Purchased Courses
                  .badge.bg-info
                    = current_user.enrollments_count
                = link_to pending_review_courses_path,  class: "dropdown-item" do
                  .fa.fa-star
                  Pending Review 
                  .badge.bg-info
                    = current_user.enrollments.pending_review.count
        - if current_user 
          - if current_user.has_role?(:teacher) 
            %li.nav-item.dropdown
              %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
                .fa.fa-chalkboard-teacher
                %b Teaching
              %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
                = link_to created_courses_path,  class: "dropdown-item" do
                  .fa.fa-graduation-cap
                  Created Courses
                  .badge.bg-info
                    = current_user.courses_count
                = link_to my_students_enrollments_path,  class: "dropdown-item" do
                  .fa.fa-lock-open
                  My students  
                  .badge.bg-info
                    = Enrollment.joins(:course).where(courses: {user: current_user}).count
                = link_to new_course_path,  class: "dropdown-item" do
                  .fa.fa-plus
                  New Course   
        
      %ul.navbar-nav.ms-auto
        - if current_user
          .form-inline
            - if @ransack_courses.present?
              = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
                .input-group
                  = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; ', placeholder: 'Find a course', :autocomplete => :off
                  %span.input-group-append
                    %button.btn.btn-outline-success{:type => "submit"} Search
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button", :style => "margin-right: 150px"}
              - if current_user.image?
                = image_tag current_user.image, size: '30x30', alt: "#{current_user.email}", class: 'rounded-circle'
              - else
                .fa.fa-user
              %b= current_user.username
            %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              = link_to user_path(current_user), class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do
                .fa.fa-cog
                %b My profile
              = link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do
                .fa.fa-cog
                %b Account settings
              = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
                .fa.fa-sign-out-alt
                %b Sign out
                
            
        - else
          %ul.navbar-nav.mr-auto
            %ul.navbar-nav.mr-right
              %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_registration_path)}", style: "margin-right: 10px"}
                = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-outline-info'
              %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_session_path)}", style: "margin-right: 10px"}
                = link_to 'Log In', new_user_session_path,  class: 'btn btn-outline-info'
              %li.nav-item{class: "#{'active font-weight-bold' if current_page?(user_google_oauth2_omniauth_authorize_path)}"}
                = link_to 'Sign in with Google', user_google_oauth2_omniauth_authorize_path, method: :post, class: 'btn btn-outline-info'  
                
                

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} alert-dismissible fade show" , :role => "alert"}
      %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    /%title EiuELearning
    %title
      = content_for?(:title) ? yield(:title) : "EiuELearning"
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container-fluid.maxWidth
      = yield
    %br
    = render 'layouts/footer'

app/views/layouts/pdf.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    = wicked_pdf_stylesheet_link_tag "pdf"
  %body{:onload => "number_pages"}
    #header
    #content
      = yield